// Fingerprint protection injected into every webview page via executeJavaScript on dom-ready.
// Uses only ES5-safe syntax to avoid any serialization issues when passed as a string.

export const FINGERPRINT_INJECT_CODE = [
  '(function() {',
  '  if (window.__gkFP) return;',
  '  window.__gkFP = true;',

  // Per-session noise: ±1, different each session
  '  var N1 = Math.random() > 0.5 ? 1 : -1;',
  '  var N2 = Math.random() > 0.5 ? 1 : -1;',

  // ── Canvas: override toDataURL to return slightly noised pixels ──
  '  var _origToDataURL = HTMLCanvasElement.prototype.toDataURL;',
  '  HTMLCanvasElement.prototype.toDataURL = function(type, quality) {',
  '    try {',
  '      if (!this.width || !this.height) return _origToDataURL.call(this, type, quality);',
  '      var off = document.createElement("canvas");',
  '      off.width = this.width; off.height = this.height;',
  '      var ctx = off.getContext("2d");',
  '      ctx.drawImage(this, 0, 0);',
  '      var img = ctx.getImageData(0, 0, off.width, off.height);',
  '      var d = img.data;',
  '      var step = Math.max(4, Math.floor(d.length / 8));',
  '      for (var i = 0; i < d.length; i += step) {',
  '        d[i]   = Math.max(0, Math.min(255, d[i]   + N1));',
  '        if (i+1 < d.length) d[i+1] = Math.max(0, Math.min(255, d[i+1] + N2));',
  '      }',
  '      ctx.putImageData(img, 0, 0);',
  '      return _origToDataURL.call(off, type, quality);',
  '    } catch(e) { return _origToDataURL.call(this, type, quality); }',
  '  };',

  // ── Canvas: override getImageData ──
  '  var _origGetImageData = CanvasRenderingContext2D.prototype.getImageData;',
  '  CanvasRenderingContext2D.prototype.getImageData = function(sx, sy, sw, sh) {',
  '    var img = _origGetImageData.call(this, sx, sy, sw, sh);',
  '    var d = img.data;',
  '    var step = Math.max(4, Math.floor(d.length / 8));',
  '    for (var i = 0; i < d.length; i += step) {',
  '      d[i]   = Math.max(0, Math.min(255, d[i]   + N1));',
  '      if (i+1 < d.length) d[i+1] = Math.max(0, Math.min(255, d[i+1] + N2));',
  '    }',
  '    return img;',
  '  };',

  // ── WebGL: spoof vendor/renderer, add noise to readPixels ──
  '  var VENDOR   = "Google Inc. (Intel)";',
  '  var RENDERER = "ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)";',
  '  var GL_VENDOR = 0x1F00, GL_RENDERER = 0x1F01;',
  '  var UNMASKED_VENDOR = 0x9245, UNMASKED_RENDERER = 0x9246;',

  '  function patchGL(proto) {',
  '    var _origGet = proto.getParameter;',
  '    proto.getParameter = function(p) {',
  '      if (p === GL_VENDOR || p === UNMASKED_VENDOR)   return VENDOR;',
  '      if (p === GL_RENDERER || p === UNMASKED_RENDERER) return RENDERER;',
  '      return _origGet.call(this, p);',
  '    };',
  '    var _origRead = proto.readPixels;',
  '    proto.readPixels = function(x, y, w, h, fmt, type, px) {',
  '      _origRead.call(this, x, y, w, h, fmt, type, px);',
  '      if (px && px.length) {',
  '        var step = Math.max(4, Math.floor(px.length / 8));',
  '        for (var i = 0; i < px.length; i += step) {',
  '          px[i] = Math.max(0, Math.min(255, px[i] + N1));',
  '        }',
  '      }',
  '    };',
  '  }',

  '  if (typeof WebGLRenderingContext !== "undefined") patchGL(WebGLRenderingContext.prototype);',
  '  if (typeof WebGL2RenderingContext !== "undefined") patchGL(WebGL2RenderingContext.prototype);',

  // ── Navigator: hide webdriver flag (Electron sets it true — Google checks this) ──
  '  try {',
  '    Object.defineProperty(navigator, "webdriver", { get: function() { return false; }, configurable: true });',
  '  } catch(e) {}',

  // ── navigator.plugins / mimeTypes: spoof Chrome PDF Viewer presence ──
  // Empty plugins array is a major Electron signal — real Chrome always has PDF viewer.
  '  try {',
  '    var makeFakePlugin = function(name, desc, fn, suffixes, types) {',
  '      var plugin = { name: name, description: desc, filename: fn, length: types.length };',
  '      types.forEach(function(t, i) {',
  '        var mt = { type: t, suffixes: suffixes[i] || "", description: desc };',
  '        Object.defineProperty(plugin, i, { value: mt, enumerable: true });',
  '      });',
  '      return plugin;',
  '    };',
  '    if (navigator.plugins.length === 0) {',
  '      var fakePlugins = [',
  '        makeFakePlugin("PDF Viewer","Portable Document Format","internal-pdf-viewer",["pdf","pdf"],["application/pdf","text/pdf"]),',
  '        makeFakePlugin("Chrome PDF Viewer","Portable Document Format","internal-pdf-viewer",["pdf","pdf"],["application/pdf","text/pdf"]),',
  '        makeFakePlugin("Chromium PDF Viewer","Portable Document Format","internal-pdf-viewer",["pdf","pdf"],["application/pdf","text/pdf"]),',
  '        makeFakePlugin("Microsoft Edge PDF Viewer","Portable Document Format","internal-pdf-viewer",["pdf","pdf"],["application/pdf","text/pdf"]),',
  '        makeFakePlugin("WebKit built-in PDF","Portable Document Format","internal-pdf-viewer",["pdf","pdf"],["application/pdf","text/pdf"])',
  '      ];',
  '      Object.defineProperty(Navigator.prototype, "plugins", {',
  '        get: function() {',
  '          var arr = fakePlugins.slice();',
  '          arr.length = fakePlugins.length;',
  '          arr.item = function(i) { return fakePlugins[i] || null; };',
  '          arr.namedItem = function(n) { return fakePlugins.find(function(p){return p.name===n;})||null; };',
  '          arr.refresh = function() {};',
  '          return arr;',
  '        },',
  '        configurable: true',
  '      });',
  '    }',
  '  } catch(e) {}',

  // ── navigator.credentials: reject publicKey so Google falls back to password instead of showing OS passkey dialog ──
  '  try {',
  '    var _origCredGet = navigator.credentials && navigator.credentials.get ? navigator.credentials.get.bind(navigator.credentials) : null;',
  '    if (_origCredGet) {',
  '      Object.defineProperty(navigator.credentials, "get", {',
  '        value: function(options) {',
  '          if (options && options.publicKey) {',
  '            return Promise.reject(new DOMException("Not supported", "NotSupportedError"));',
  '          }',
  '          return _origCredGet(options);',
  '        },',
  '        configurable: true',
  '      });',
  '    }',
  '  } catch(e) {}',

  // ── Navigator: normalize identifying hardware metrics ──
  '  try {',
  '    Object.defineProperty(Navigator.prototype, "hardwareConcurrency", { get: function() { return 4; }, configurable: true });',
  '  } catch(e) {}',
  '  try {',
  '    Object.defineProperty(Navigator.prototype, "deviceMemory", { get: function() { return 8; }, configurable: true });',
  '  } catch(e) {}',

  // ── navigator.userAgentData: remove Electron brand, spoof as Chrome ──
  // Google sign-in reads this JS API to detect embedded browsers.
  '  try {',
  '    var _chromeMatch = navigator.userAgent.match(/Chrome\\/([\\d.]+)/);',
  '    var _fullVer = _chromeMatch ? _chromeMatch[1] : "136.0.7103.115";',
  '    var _majorVer = _fullVer.split(".")[0];',
  '    var _brands = [',
  '      { brand: "Google Chrome", version: _majorVer },',
  '      { brand: "Not)A;Brand", version: "8" },',
  '      { brand: "Chromium", version: _majorVer }',
  '    ];',
  '    var _fullBrands = [',
  '      { brand: "Google Chrome", version: _fullVer },',
  '      { brand: "Not)A;Brand", version: "8.0.0.0" },',
  '      { brand: "Chromium", version: _fullVer }',
  '    ];',
  '    var _uaData = {',
  '      brands: _brands,',
  '      mobile: false,',
  '      platform: "Windows",',
  '      getHighEntropyValues: function(hints) {',
  '        var result = { brands: _brands, mobile: false, platform: "Windows" };',
  '        if (hints.indexOf("architecture") !== -1) result.architecture = "x86";',
  '        if (hints.indexOf("bitness") !== -1) result.bitness = "64";',
  '        if (hints.indexOf("platformVersion") !== -1) result.platformVersion = "15.0.0";',
  '        if (hints.indexOf("uaFullVersion") !== -1) result.uaFullVersion = _fullVer;',
  '        if (hints.indexOf("fullVersionList") !== -1) result.fullVersionList = _fullBrands;',
  '        if (hints.indexOf("wow64") !== -1) result.wow64 = false;',
  '        if (hints.indexOf("model") !== -1) result.model = "";',
  '        return Promise.resolve(result);',
  '      },',
  '      toJSON: function() { return { brands: _brands, mobile: false, platform: "Windows" }; }',
  '    };',
  '    Object.defineProperty(Navigator.prototype, "userAgentData", {',
  '      get: function() { return _uaData; },',
  '      configurable: true',
  '    });',
  '  } catch(e) {}',

  // ── window.chrome: spoof the Chrome extension runtime object ──
  // Google's risk-assessment script checks for window.chrome.runtime.  Its
  // absence is one of the strongest signals that the page is running in a
  // non-Chrome host (Electron webview, headless, etc.).
  '  try {',
  '    if (!window.chrome || !window.chrome.runtime) {',
  '      var _st = Date.now();',
  '      window.chrome = {',
  '        app: {',
  '          isInstalled: false,',
  '          InstallState: { DISABLED:"disabled", INSTALLED:"installed", NOT_INSTALLED:"not_installed" },',
  '          RunningState: { CANNOT_RUN:"cannot_run", READY_TO_RUN:"ready_to_run", RUNNING:"running" },',
  '          getDetails: function() { return null; },',
  '          getIsInstalled: function() { return false; },',
  '          installState: function(cb) { cb("not_installed"); },',
  '          runningState: function() { return "cannot_run"; }',
  '        },',
  '        runtime: {',
  '          OnInstalledReason: { CHROME_UPDATE:"chrome_update", INSTALL:"install", SHARED_MODULE_UPDATE:"shared_module_update", UPDATE:"update" },',
  '          OnRestartRequiredReason: { APP_UPDATE:"app_update", OS_UPDATE:"os_update", PERIODIC:"periodic" },',
  '          PlatformArch: { ARM:"arm", ARM64:"arm64", MIPS:"mips", MIPS64:"mips64", X86_32:"x86-32", X86_64:"x86-64" },',
  '          PlatformOs: { ANDROID:"android", CROS:"cros", LINUX:"linux", MAC:"mac", OPENBSD:"openbsd", WIN:"win" },',
  '          RequestUpdateCheckStatus: { NO_UPDATE:"no_update", THROTTLED:"throttled", UPDATE_AVAILABLE:"update_available" },',
  '          connect: function() {},',
  '          sendMessage: function() {}',
  '        },',
  '        csi: function() { return { startE: _st, onloadT: _st + 120, pageT: Date.now() - _st, tran: 15 }; },',
  '        loadTimes: function() {',
  '          return { commitLoadTime: _st/1000, connectionInfo:"h2", finishDocumentLoadTime:(_st+300)/1000,',
  '            finishLoadTime:(_st+400)/1000, firstPaintAfterLoadTime:0, firstPaintTime:(_st+250)/1000,',
  '            navigationType:"Other", npnNegotiatedProtocol:"h2", requestTime:_st/1000,',
  '            startLoadTime:(_st+10)/1000, wasAlternateProtocolAvailable:false, wasFetchedViaSpdy:true, wasNpnNegotiated:true };',
  '        }',
  '      };',
  '    }',
  '  } catch(e) {}',

  // ── AudioContext: tiny noise on frequency data ──
  '  try {',
  '    var _origGetFloat = AnalyserNode.prototype.getFloatFrequencyData;',
  '    AnalyserNode.prototype.getFloatFrequencyData = function(arr) {',
  '      _origGetFloat.call(this, arr);',
  '      if (arr && arr.length) arr[0] += N1 * 0.0001;',
  '    };',
  '  } catch(e) {}',

  '})();',
].join('\n');
